import uuid
import json
import os
class MemoryManager:
    def __init__(self):
        # In-memory storage dictionary 
        self.sessions = {}
        self.output_dir = "data/outputs"
        os.makedirs(self.output_dir, exist_ok=True)
    def create_new_session(self, file_path):
        """Creates a unique ID for the user session."""
        session_id = str(uuid.uuid4())
        self.sessions[session_id] = {
            "history": [],
            "file_path": file_path,
            "input_context": None  
        }
        return session_id
    def get_session_data(self, session_id):
        """Retrieves session data by ID."""
        return self.sessions.get(session_id)

    def get_history(self, session_id):
        """Retrieves the full conversation history for a given session ID."""
        session = self.get_session_data(session_id)
        if session and "history" in session:
            return session["history"]
        return []

    def save_input_context(self, session_id, content_data):
        """Saves the extracted file content context into the session."""
        if session_id in self.sessions:
            self.sessions[session_id]["input_context"] = content_data
        

    
    def add_turn(self, session_id, user_msg, model_msg):
        """Adds a user-model exchange to the history."""
        if session_id in self.sessions:
            self.sessions[session_id]["history"].append({"role": "user", "parts": [user_msg]})
            self.sessions[session_id]["history"].append({"role": "model", "parts": [model_msg]})
    def save_final_json(self, session_id, json_string):
        """Saves the final JSON string to a file."""
        # Clean the string 
        clean_json = json_string.replace("```json", "").replace("```", "").strip()
        try:
            data = json.loads(clean_json)
            file_path = f"{self.output_dir}/{session_id}_summary.json"
            with open(file_path, 'w', encoding='utf-8') as f:
                json.dump(data, f, ensure_ascii=False, indent=4)
            return {"status": "success", "file_path": file_path, "data": data}
        except json.JSONDecodeError:
            return {"status": "error", "detail": "Invalid JSON format generated by AI"}